### PR TITLE
added isJSON() method

### PR DESCRIPTION
**Pull request by umermansoor**
Added a new method to check for is JSON content type: isJSON()

### CODE REVIEW

**Comment by domenic** [comment]
Can you explain the use case for this?

Also, this doesn't meet the definition of https://mimesniff.spec.whatwg.org/#json-mime-type

**Comment by umermansoor** [comment]
> Can you explain the use case for this?

Detect JSON so it can be prettified with the correct library e.g. js-beautify vs xml-beautify...

> Also, this doesn't meet the definition of https://mimesniff.spec.whatwg.org/#json-mime-type

text/json doesn't seem to listed in supported types, but I'll add. Regarding +json, I did add ld+json but I'll make it generic. https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types

**Comment by domenic** [comment]
> Detect JSON so it can be prettified with the correct library e.g. js-beautify vs xml-beautify...

Do you have a specific project that uses this as a dependency and plans to use this feature?

> text/json doesn't seem to listed in supported types, but I'll add. Regarding +json, I did add ld+json but I'll make it generic. https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types

You still have not implemented the spec correctly. Please implement the spec as written, and extend the test cases. E.g. `anything/foo+json` should pass. `text/json` should pass. Etc.

Our reference is the specification, not an MDN page.

**Comment by fastfedora** [comment]
I know this is an old PR, so isn't likely to be merged. But since I needed the same functionality, I figured I'd post my solution here, in case it's useful for anyone else who stumbles across this. My use case for `isJson` is to select the correct body retrieval and/or parsing method in a generic API adapter.

```
type ContentFormat = 'json' | 'xml' | 'html' | 'text';

const isJson = (mimeType: MIMEType): boolean => (
  ['application/json', 'text/json'].includes(mimeType.essence) || mimeType.subtype.endsWith('+json')
);

function parseContentFormat(contentType: string): ContentFormat | undefined {
  const mimeType = new MIMEType(contentType);

  if (mimeType.isXML()) {
    return 'xml';
  } else if (mimeType.isHTML()) {
    return 'html';
  } else if (isJson(mimeType)) {
    return 'json';
  } else if (mimeType.essence === 'text/plain') {
    return 'text';
  }

  return undefined;
}

async parseBody(response: Response): Promise<any> {
  const contentFormat = parseContentFormat(response.headers.get('content-type'));

  switch (contentFormat) {
    case 'json':
      return await response.json();

    case 'xml':
      return parseXml(await response.text());
    
    case 'html':
      return parseHtml(await response.text());

    case 'text':
      return await response.text();

    default:
      console.warn(`Missing or invalid content type on request: ${contentFormat}`);
      return await response.text();
  }    
}
```

**Comment by domenic** [comment]
I've decided not to add further type-testing methods to this package; thanks for your interest.

**Pull request closed without merging**
